---
title: "ResearchExperience"
about:
  template: jolla
---


<div class="box">

**Montana State University** 2024-present

- Investigate the interaction between plant herbivore tolerance and trait-based responses to abiotic stress

</div>

<div class="box">

**Penn State Entomology** 2022-2024

- Manage the entomology component of Common Experiment 2 (16 states) of the Precision Sustainable Agriculture Grant 
  - Responsibilities include protocol troubleshooting, data collection, whole-team data flow and analyses, and fieldwork
- Augmentation experiment
  - Working to quantify the role web-building spiders have as biological control agents in conventional soybeans
- Agroecosystem health
  - Partnered with the [Rodale Institute](https://rodaleinstitute.org/) 
  - Using microarthropods as biological indicators to determine the ecosystem quality of different agricultural practices/ land-uses
      - E.g., legacy no-till vs. till, organic vs. conventional, etc. 

</div>

<div class="box">

**Penn State Weed Science** 2021-2022

- Managed three projects of the Precision Sustainable Agriculture Grant for [Dr. John Wallace](https://plantscience.psu.edu/directory/jmw309) 
  - Common Experiment 1 ([CE1](https://www.precisionsustainableag.org/ce1)): Nitrogen Cycling
  - Common Experiment 2 ([CE2](https://www.precisionsustainableag.org/ce2)): Inter-disciplinary pest interactions
  - On-Farm ([OF](https://www.precisionsustainableag.org/on-farm)): Implementing similar field management practices from CE1 and 2 with Pennsylvania growers 

</div>

<div class="box">

**Lehigh Agricultural and Biological Services** 2020-2021

</div>
